export const MOVIES: any = {
  1: {
    id: 1,
    movie: 'The Avengers',
    genre: ['action', 'adventure', 'sci-fi'],
    description: 'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',
    yearOfMake: '2012',
    imageUrl: 'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/55/Trailer20036layer42.png/revision/latest/scale-to-width-down/1000?cb=20210502193413',
  },
  2: {
    id: 2,
    movie: 'Avengers: Endgame',
    genre: ['action', 'adventure', 'drama'],
    description: 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
    yearOfMake: '2019',
    imageUrl: 'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e8/I..._am..._Iron_Man.png/revision/latest/scale-to-width-down/1000?cb=20200701004602',
  },
  3: {
    id: 3,
    movie: 'Avengers: Infinity War',
    genre: ['action', 'adventure', 'sci-fi'],
    description: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
    yearOfMake: '2018',
    imageUrl: 'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/52/TVspot-18.png/revision/latest/scale-to-width-down/1000?cb=20210508011844',
  },
  4: {
    id: 4,
    movie: 'Iron Man',
    genre: ['action', 'adventure', 'sci-fi'],
    description: 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
    yearOfMake: '2008',
    imageUrl: 'https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/41/Iron_Man_Mark_III_in_Flight.jpg/revision/latest/scale-to-width-down/570?cb=20140906060402',
  },
  5: {
    id: 5,
    movie: 'The Lord of the Rings: The Fellowship of the Ring',
    genre: ['action', 'adventure', 'drama'],
    description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    yearOfMake: '2001',
    imageUrl: 'https://images.unsplash.com/photo-1600003251514-239257fb4c53?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGxvcmQlMjBvZiUyMHRoZSUyMHJpbmdzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  },
  6: {
    id: 6,
    movie: 'The Lord of the Rings: The Two Towers',
    genre: ['action', 'adventure', 'drama'],
    description: 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman, and his hordes of Isengard.',
    yearOfMake: '2002',
    imageUrl: 'https://images.unsplash.com/photo-1624489094663-a51a6c61d492?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGxvcmQlMjBvZiUyMHRoZSUyMHJpbmdzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  },
  7: {
    id: 7,
    movie: 'Hitman: Agent 47',
    genre: ['action', 'crime', 'thriller'],
    description: 'An assassin teams up with a woman to help her find her father and uncover the mysteries of her ancestry.',
    yearOfMake: '2015',
    imageUrl: 'https://images.unsplash.com/photo-1585951237318-9ea5e175b891?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGFjdGlvbnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  },
  8: {
    id: 8,
    movie: 'Into the Storm',
    genre: ['action', 'adventure', 'drama'],
    description: 'Storm trackers, thrill-seekers, and everyday townspeople document an unprecedented onslaught of tornadoes touching down in the town of Silverton.',
    yearOfMake: '2014',
    imageUrl: 'https://images.unsplash.com/photo-1431440869543-efaf3388c585?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  },
}
